---

- hosts: all
  become: true
  tasks:

  - name: install apache and php packages for ubuntu
    apt:
      name: 
        - apache2
        - libapach2-mod-php
      state: latest
      update_cache: yes
      when: ansible_distribution == "Ubuntu"

      
    

  

  
