---

- hosts: all
  become: true
  pre_tasks:

  - name: install apache and php packages for ubuntu
    tags: always
    apt:
      upgrade: dist 
      update_cache: yes
    
    when: ansible_distribution == "Ubuntu"


- hosts: web_servers
  become: true
  tasks:

    - name: install apache and php for ubuntu servers
      tags: apache,apache2,ubuntu
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution =="Ubuntu"
           
     
- hosts: db_servers
  become: true
  tasks:
   
   - name: install maria package(Ubuntu)
     tags: centos,db,mariadb
     apt: 
       name: mariadb-server
       state: latest
     when: ansible_distribution == "Ubuntu"
    

  

  
